# Generated by Django 5.2 on 2025-04-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quote_type',
            field=models.CharField(choices=[('english_quote', 'English Quote'), ('tamil_quote', 'Tamil Quote')], default='english_quote', max_length=255),
        ),
    ]
