# Generated by Django 5.2 on 2025-04-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='product_size',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
